### ISSUE TITLE
I think I found a bug in your code regarding iat in your function **MergeUserClaimsWithDefaultClaims**

### ISSUE THREAD

**Issue by explorer14** [explorer14/JwtAuthenticationHelper#2]
I think I found a bug in your code regarding iat in your function **MergeUserClaimsWithDefaultClaims**

//I think this is incorrect - should be seconds since 1970
new Claim(JwtRegisteredClaimNames.Iat, DateTime.UtcNow.TimeOfDay.Ticks.ToString(), ClaimValueTypes.Integer64)

//My fix
long seconds = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
new Claim(JwtRegisteredClaimNames.Iat,seconds.ToString(),ClaimValueTypes.Integer64)

_Originally posted by @Weboholics in https://github.com/explorer14/JwtAuthenticationHelper/issues/1#issuecomment-541035063_

**Comment by explorer14** [comment]
@Weboholics, thanks for raising this issue. I think you might be right because according to [RFC](https://tools.ietf.org/html/rfc7519#section-4.1.6) the `iat` claim is specified as a NumericDate value which is: 

> _A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1, 2013 Edition [POSIX.1] definition "Seconds Since the Epoch"..._

Please make a PR for this fix if you'd like. 👍 

Cheers
Aman

**Comment by Weboholics** [comment]
Thanks!
I have had good use of your code :-)
I will create a PR

**Comment by Weboholics** [comment]
Hm... PR seems harder than I thought. I have never created a PR. Could you do it?

**Comment by explorer14** [comment]
This has been addressed @Weboholics ! Cheers for pointing this out! Here's the commit that fixes this: https://github.com/explorer14/JwtAuthenticationHelper/commit/f5678db0542020cd6109bdfcf8a1a1622c1600ef
