### ISSUE TITLE
CryptographicException: The key {0b666a11-3dd1-4c3e-a2ff-36606637c627} was not found in the key ring.

### ISSUE THREAD

**Issue by petersontubini** [explorer14/JwtAuthenticationHelper#4]
How I can return a 401 Unauthorized instead of giving that ugly exception when a cookie is invalid?

**Comment by explorer14** [comment]
Hey @petersontubini , have you already figured this out or is this still a problem for you? Sorry, been crazy for the last couple of months with the whole pandemic thing and remote working, haven't really been paying attention to this repo. Please let me know if this is still a problem for you and I will take a look, I will keep this issue open until then! Cheers

**Comment by explorer14** [comment]
Closing due to no response!
